#!/usr/bin/env python3
import os
import subprocess
import html

INPUT_PATH = "/home/ghost/iON/cases/pcr/CodyRedmond_20250011928_BWL7044188-0_merged.txt"
OUTPUT_DIR = "/home/ghost/iON/cases/pcr"
HTML_PATH = os.path.join(OUTPUT_DIR, "CodyRedmond_20250011928_BWL7044188-0_report.html")
PDF_PATH = os.path.join(OUTPUT_DIR, "CodyRedmond_20250011928_BWL7044188-0_report.pdf")

def main():
    # Read transcript
    with open(INPUT_PATH, "r") as f:
        lines = f.readlines()

    # Build transcript rows
    rows = []
    for line in lines:
        line = line.strip()
        if not line:
            continue
        # Parse format: [   0.00s -    2.06s] SPEAKER_XX: text
        if line.startswith("[") and "]" in line:
            time_part, rest = line.split("]", 1)
            time_part = time_part.strip("[] ")
            rest = rest.strip()
            if ":" in rest:
                speaker, text = rest.split(":", 1)
                speaker = speaker.strip()
                text = text.strip()
            else:
                speaker = "UNKNOWN"
                text = rest
        else:
            time_part = ""
            speaker = "UNKNOWN"
            text = line

        speaker_class = speaker.lower().replace("_", "-")
        rows.append((time_part, speaker, html.escape(text), speaker_class))

    # Build HTML
    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Case Transcript Report</title>
<style>
@page {{ size: letter; margin: 0.75in; }}
body {{
    font-family: "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    font-size: 11pt;
    line-height: 1.6;
    color: #1a1a1a;
    max-width: 7in;
    margin: 0 auto;
}}
.header {{
    border-bottom: 2px solid #2c3e50;
    padding-bottom: 12px;
    margin-bottom: 24px;
}}
.header h1 {{
    font-size: 18pt;
    color: #2c3e50;
    margin: 0 0 6px 0;
}}
.header .meta {{
    font-size: 10pt;
    color: #555;
}}
.entry {{
    margin-bottom: 10px;
    page-break-inside: avoid;
}}
.time {{
    font-size: 9pt;
    color: #666;
    font-variant-numeric: tabular-nums;
    min-width: 140px;
    display: inline-block;
}}
.speaker {{
    font-weight: 700;
    font-size: 9.5pt;
    text-transform: uppercase;
    letter-spacing: 0.3px;
    min-width: 90px;
    display: inline-block;
}}
.speaker-00 {{ color: #1f4e79; }}
.speaker-01 {{ color: #8b0000; }}
.speaker-02 {{ color: #006400; }}
.speaker-unknown {{ color: #888; }}
.text {{
    display: inline;
}}
.footer {{
    margin-top: 30px;
    padding-top: 10px;
    border-top: 1px solid #ccc;
    font-size: 9pt;
    color: #777;
    text-align: center;
}}
</style>
</head>
<body>
<div class="header">
    <h1>Transcript & Speaker Diarization Report</h1>
    <div class="meta">
        <strong>Subject:</strong> Cody Redmond &nbsp;|&nbsp;
        <strong>Case #:</strong> BWL7044188-0 &nbsp;|&nbsp;
        <strong>Date:</strong> 2025-10-01 &nbsp;|&nbsp;
        <strong>Source:</strong> Body-Worn Camera Audio
    </div>
</div>
"""

    for time_part, speaker, text, speaker_class in rows:
        html_content += f"""<div class="entry">
    <span class="time">{html.escape(time_part)}</span>
    <span class="speaker {speaker_class}">{html.escape(speaker)}</span>
    <span class="text">{text}</span>
</div>
"""

    html_content += """<div class="footer">
Generated by iON Data Security Systems &mdash; Whisper Small + pyannote.audio 3.1
</div>
</body>
</html>"""

    with open(HTML_PATH, "w") as f:
        f.write(html_content)

    print(f"HTML saved to {HTML_PATH}")
    print("Converting to PDF with LibreOffice...")
    result = subprocess.run([
        "libreoffice", "--headless", "--convert-to", "pdf",
        "--outdir", OUTPUT_DIR, HTML_PATH
    ], capture_output=True, text=True)

    if result.returncode != 0:
        print("LibreOffice stderr:", result.stderr)
        raise RuntimeError("PDF conversion failed")

    print(f"PDF saved to {PDF_PATH}")

if __name__ == "__main__":
    main()
