// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function ProcessBackup(arg1:string):Promise<string>;

export function StartExtraction(arg1:string):Promise<void>;
