// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchMessageAction(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BatchMessageAction'](arg1, arg2, arg3, arg4);
}

export function CreateCaseFromBackup(arg1, arg2) {
  return window['go']['main']['App']['CreateCaseFromBackup'](arg1, arg2);
}

export function DecryptBackup(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DecryptBackup'](arg1, arg2, arg3, arg4);
}

export function ExportEvidence(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportEvidence'](arg1, arg2, arg3);
}

export function ExportMessageQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportMessageQuery'](arg1, arg2, arg3);
}

export function GetAgent(arg1) {
  return window['go']['main']['App']['GetAgent'](arg1);
}

export function GetAgentCatalog() {
  return window['go']['main']['App']['GetAgentCatalog']();
}

export function GetCaseSummary(arg1) {
  return window['go']['main']['App']['GetCaseSummary'](arg1);
}

export function GetDeviceStatus() {
  return window['go']['main']['App']['GetDeviceStatus']();
}

export function GetEvidenceRecords(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetEvidenceRecords'](arg1, arg2, arg3, arg4);
}

export function GetEvidenceSummary(arg1, arg2) {
  return window['go']['main']['App']['GetEvidenceSummary'](arg1, arg2);
}

export function GetInstalledApps(arg1) {
  return window['go']['main']['App']['GetInstalledApps'](arg1);
}

export function GetMessageContacts(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetMessageContacts'](arg1, arg2, arg3, arg4);
}

export function GetMessageIndexStatus(arg1) {
  return window['go']['main']['App']['GetMessageIndexStatus'](arg1);
}

export function GetMessageThreads(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetMessageThreads'](arg1, arg2, arg3, arg4, arg5);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListAppFiles(arg1) {
  return window['go']['main']['App']['ListAppFiles'](arg1);
}

export function ListCases() {
  return window['go']['main']['App']['ListCases']();
}

export function ListEvidenceTypes(arg1) {
  return window['go']['main']['App']['ListEvidenceTypes'](arg1);
}

export function MountDevice(arg1) {
  return window['go']['main']['App']['MountDevice'](arg1);
}

export function OpenAppContainer(arg1) {
  return window['go']['main']['App']['OpenAppContainer'](arg1);
}

export function OpenAttachment(arg1) {
  return window['go']['main']['App']['OpenAttachment'](arg1);
}

export function PairDevice(arg1) {
  return window['go']['main']['App']['PairDevice'](arg1);
}

export function PrepareMessageIndex(arg1) {
  return window['go']['main']['App']['PrepareMessageIndex'](arg1);
}

export function ProcessBackup(arg1, arg2) {
  return window['go']['main']['App']['ProcessBackup'](arg1, arg2);
}

export function PullBackup(arg1) {
  return window['go']['main']['App']['PullBackup'](arg1);
}

export function QueryMessages(arg1, arg2) {
  return window['go']['main']['App']['QueryMessages'](arg1, arg2);
}

export function ReadAppFile(arg1) {
  return window['go']['main']['App']['ReadAppFile'](arg1);
}

export function RefreshDeviceTrust() {
  return window['go']['main']['App']['RefreshDeviceTrust']();
}

export function SearchAppData(arg1, arg2) {
  return window['go']['main']['App']['SearchAppData'](arg1, arg2);
}

export function SelectBackupDirectory() {
  return window['go']['main']['App']['SelectBackupDirectory']();
}

export function StartExtraction(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartExtraction'](arg1, arg2, arg3);
}

export function StopExtraction() {
  return window['go']['main']['App']['StopExtraction']();
}

export function UnmountDevice(arg1) {
  return window['go']['main']['App']['UnmountDevice'](arg1);
}

export function UnpairDevice(arg1) {
  return window['go']['main']['App']['UnpairDevice'](arg1);
}

export function ValidatePairing(arg1) {
  return window['go']['main']['App']['ValidatePairing'](arg1);
}
