// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BatchMessageAction(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<main.MessageActionResult>;

export function CreateCaseFromBackup(arg1:string,arg2:string):Promise<string>;

export function DecryptBackup(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ExportEvidence(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExportMessageQuery(arg1:string,arg2:main.MessageQuery,arg3:string):Promise<main.MessageExportResult>;

export function GetAgent(arg1:string):Promise<main.AgentCatalog>;

export function GetAgentCatalog():Promise<Array<main.AgentCatalog>>;

export function GetCaseSummary(arg1:string):Promise<main.CaseSummary>;

export function GetDeviceStatus():Promise<main.DeviceStatus>;

export function GetEvidenceRecords(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<Record<string, any>>>;

export function GetEvidenceSummary(arg1:string,arg2:string):Promise<main.EvidenceSummary>;

export function GetInstalledApps(arg1:string):Promise<Array<main.InstalledApp>>;

export function GetMessageContacts(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.MessageContactPage>;

export function GetMessageIndexStatus(arg1:string):Promise<main.MessageIndexStatus>;

export function GetMessageThreads(arg1:string,arg2:Array<string>,arg3:string,arg4:number,arg5:number):Promise<main.MessageThreadPage>;

export function Greet(arg1:string):Promise<string>;

export function ListAppFiles(arg1:string):Promise<Array<main.AppFile>>;

export function ListCases():Promise<Array<string>>;

export function ListEvidenceTypes(arg1:string):Promise<Array<string>>;

export function MountDevice(arg1:string):Promise<string>;

export function OpenAppContainer(arg1:string):Promise<void>;

export function OpenAttachment(arg1:string):Promise<void>;

export function PairDevice(arg1:string):Promise<void>;

export function PrepareMessageIndex(arg1:string):Promise<main.MessageIndexStatus>;

export function ProcessBackup(arg1:string,arg2:string):Promise<string>;

export function PullBackup(arg1:string):Promise<void>;

export function QueryMessages(arg1:string,arg2:main.MessageQuery):Promise<main.MessagePage>;

export function ReadAppFile(arg1:string):Promise<string>;

export function RefreshDeviceTrust():Promise<main.DeviceStatus>;

export function SearchAppData(arg1:string,arg2:string):Promise<Array<main.AppDataHit>>;

export function SelectBackupDirectory():Promise<string>;

export function StartExtraction(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StopExtraction():Promise<void>;

export function UnmountDevice(arg1:string):Promise<void>;

export function UnpairDevice(arg1:string):Promise<void>;

export function ValidatePairing(arg1:string):Promise<void>;
